### ISSUE TITLE
merlinkey.py should use proper prefix directory

### ISSUE THREAD

**Issue by eschoeller** [ITRS-Group/monitor-merlin#115]
When using a different prefix directory, the merlinkey.py should likely have an updated 'merlin_conf_dir' to reflect that. 

Also, the '/usr/lib64/merlin/keygen' path is also wrong and does not reflect the prefix used in configure. 

I do realize the introduction states:
"Non-customers will have to adjust paths etc used throughout this guide in order to be able to use it." So, if that's the case for these two little issues then no big deal:)

**Comment by jacobbaungard** [comment]
Right, that is not ideal. Thanks for sending it in.
