### ISSUE TITLE
Instruction for standalone server

### ISSUE THREAD

**Issue by geekmichael** [ITRS-Group/monitor-merlin#17]
Hi, I am trying to configure Naemon, merlin and Ninja with just one server. The current instruction does not have information about how to configure merlin without peer and pool. Meanwhile, how to check the merlin running status without mon command? PS. I really don't know where to get this command.

**Comment by jacobbaungard** [comment]
Hi,

I will close this old issue, assuming it is no longer relevant. These days we build RPM packages for easier installation including the `mon` command. Instructions can be found here: https://itrs-group.github.io/monitor-merlin/

Feel free to open a new issue if you are still having issues.
