### ISSUE TITLE
Downloaded merlin v2018.i.1.tar.gz tarball and autogen.sh fails

### ISSUE THREAD

**Issue by edgarm1964** [ITRS-Group/monitor-merlin#28]
LS,

  I've downloaded the merlin tarball v2018.i.1.tar.gz and tried to run auto.gen.sh.
Which fails with these errors:

merlin-2018.i.1$ ./autogen.sh --help
fatal: Not a git repository (or any of the parent directories): .git
configure.ac:4: error: AC_INIT should be called with package and version arguments
/usr/share/aclocal-1.13/init.m4:23: AM_INIT_AUTOMAKE is expanded from...
configure.ac:4: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
./autogen.sh: line 4: ./configure: No such file or directory

And no, configure does not exist.

Kind regards, Edgar Matzinger.

**Comment by jacobbaungard** [comment]
Hi,

Currently building Merlin requires you to checkout the git repo, rather than using the tarball, sorry for that.

The workaround is simply:

`
git clone https://github.com/op5/merlin.git
cd merlin
git checkout v2018.i.1
`

**Comment by edgarm1964** [comment]
Hi Jacob,

   yes, that's what I tested next... :-)

Thank you, kind regards, Edgar Matzinger.

**Comment by jacobbaungard** [comment]
Closing this old issue. Hope it worked out in the end!
