### ISSUE TITLE
Merlin wipes backlog on restart

### ISSUE THREAD

**Issue by dirtyren** [ITRS-Group/monitor-merlin#29]
Hello,
 I've been testing merlin with naemon for the past couple of weeks and I noticed that, if the connection between master and poller is down and meanwhile the master configuration is changed, when the link is back on, the master will trigger a configuration sync to the poller, which is expected.
    Up until here all is good and expected, but, while the link was down, the poller was writing its checks to the binlog, all nice, but, when the link is back and sync is triggered, the naemon + merlin must be restarted in the poller so it can sync again and when this is done, the binlog is wiped / deleted from the disk and all events are lost.
    The question is, am I doing something wrong here? I noticed the function binlog_create  uses BINLOG_UNLINK  as a flag, I changed it to BINLOG_APPEND hopping to fix this, which it did not work.
   If the configuration is not changed, merlin will sync the backlog correctly every time the link is back on perfectly.
   Merlind is set up, but I am not sending any data to the database, so I gather, I dont need really it or this is my problem?
    Tks a lot for any input here.

**Comment by jacobbaungard** [comment]
Thanks for sending this in. This matches with a known issue we have logged internally: https://jira.op5.com/browse/MON-10734

I am not 100% sure if there will be any consequences of not wiping the binlog when merlin shuts down, but likely it should be possible.

FYI the binlog is wiped in module.c line 1646 if you would like to experiment.

**Comment by dirtyren** [comment]
Tks @jacobbaungard , I tested with BINLOG_APPEND, it did not wipe the binlog but it lost past data anyway.
   I guess what is missing is that merlin-mod should check on start if there is a binlog and handle it. Is this correct?

**Comment by jacobbaungard** [comment]
@dirtyren sounds reasonable, yes.

**Comment by dirtyren** [comment]
Tks @jacobbaungard.
  I just checked the bug on OP5 jira. I also set binlog_max_memory_size = 0 in the probe, as I thought it was loosing data that was in memory on restart, but it was't the case.

**Comment by jacobbaungard** [comment]
I am looking at this a bit when I have spare time - haven't forgotten this issue!

I don't think we really need to send the binlog at startup, it would probably send it quite quickly. However I think we need to figure out the size of the file binlog at startup, so `binlog_num_entries` returns the correct count. Then I think merlin would send the binlog to nodes as appropriate shortly after startup.

I'll see if I can figure it out.

**Comment by jacobbaungard** [comment]
Finally closed by https://github.com/ITRS-Group/monitor-merlin/commit/186a6f5508a32fb829676725cc0c4cfca0f449ab !
